# Rift config

[settings]
animate = false
focus_follows_mouse = false
mouse_follows_focus = false
mouse_hides_on_focus = false
hot_reload = true

# Spaces are managed by default (not disabled)
default_disable = false

[settings.layout]
mode = "traditional"

[settings.layout.gaps.outer]
top = 0
left = 0
bottom = 0
right = 0

[settings.layout.gaps.inner]
horizontal = 0
vertical = 0

[virtual_workspaces]
enabled = true
default_workspace_count = 4
auto_assign_windows = true
preserve_focus_per_workspace = true
workspace_auto_back_and_forth = false
workspace_names = ["first", "second", "third", "fourth"]

[modifier_combinations]
comb1 = "Alt + Shift"

[keys]
"Alt + Z" = "toggle_space_activated"

"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }

"comb1 + H" = { move_node = "left" }
"comb1 + J" = { move_node = "down" }
"comb1 + K" = { move_node = "up" }
"comb1 + L" = { move_node = "right" }

"Alt + 0" = { switch_to_workspace = 0 }
"Alt + 1" = { switch_to_workspace = 1 }
"Alt + 2" = { switch_to_workspace = 2 }
"Alt + 3" = { switch_to_workspace = 3 }

"comb1 + 0" = { move_window_to_workspace = 0 }
"comb1 + 1" = { move_window_to_workspace = 1 }
"comb1 + 2" = { move_window_to_workspace = 2 }
"comb1 + 3" = { move_window_to_workspace = 3 }

"Alt + Tab" = "switch_to_last_workspace"
"Alt + Shift + Space" = "toggle_window_floating"
"Alt + F" = "toggle_fullscreen"
